const HEAVENS_GATE = [48, 49, 50, 51, 52, 53, 54];

function isHeavensGate( card ) {
    return HEAVENS_GATE.some( index => index === card.id );
}

const CHAOS = [
    new Card( "0",  "Chaos", "Amnesia",                  4, "Remove a player’s Technology or Doctrine advancement" ),
    new Card( "1",  "Chaos", "Assimilation",             4, "Double the strength of an Annexation" ),
    new Card( "2",  "Chaos", "Benefactor",               4, "Receive 15WB to use during an Auction" ),
    new Card( "3",  "Chaos", "Bounty",                   4, "Place a bounty on another player; when a tile controlled with units by that player is taken, the player that took it receives 15WB" ),
    new Card( "4",  "Chaos", "Bulldozers",               4, "For 1 round, units receive +1 on combat rolls" ),
    new Card( "5",  "Chaos", "Calling the Shots",        4, "Before an election, announce you are using this card and abstain from voting; write down your prediction for the winner and if you are correct receive 20WB" ),
    new Card( "6",  "Chaos", "Cargo Hull",               4, "Do not discard Chaos Cards during the Annual Restock" ),
    new Card( "7",  "Chaos", "Cease-Fire",               4, "No player can battle you for 1 round (Note: unoccupied districts may still be taken)" ),
    new Card( "8",  "Chaos", "Chaos Shuffle",            4, "Each player passes their Chaos Cards to the left" ),
    new Card( "9",  "Chaos", "Church and State",         4, "Players must pay you 2WB for every district they have with a religion you founded" ),
    new Card( "10", "Chaos", "Clone Army",               4, "Duplicate all units that are not Heroes, Godhands, or Killer Robots" ),
    new Card( "11", "Chaos", "Copy-Cats",                4, "For 1 round, receive 1 Faction-specific ability" ),
    new Card( "12", "Chaos", "Coup d’état",              4, "Kill all the units in another player’s Capital" ),
    new Card( "13", "Chaos", "Coward’s Way Out",         4, "Retreat at any point during a battle; retreat into any adjacent tile—even one with another player’s units—besides the original tile for the attacker" ),
    new Card( "14", "Chaos", "Critical Hit",             4, "During a battle, if an enemy unit survives because of a hit deflection, kill that unit" ),
    new Card( "15", "Chaos", "D-Day",                    4, "Choose a district and for 1 round, units receive +1 on combat rolls when invading that district and receive 1WB for each friendly unit that dies" ),
    new Card( "16", "Chaos", "Dark Ages",                4, "For 1 round, choose 1 player who cannot research advancements" ),
    new Card( "17", "Chaos", "Defectors",                4, "Take 1 unit that is not a Godhand or Hero from each player and place them in your own district as your units" ),
    new Card( "18", "Chaos", "Deserters",                4, "Remove 3 enemy units from the map" ),
    new Card( "19", "Chaos", "Distinguished Diplomat",   4, "Receive an extra 5 votes during the Continental Elections" ),
    new Card( "20", "Chaos", "Ditto",                    4, "Copy another card already played" ),
    new Card( "21", "Chaos", "Ditto",                    4, "Copy another card already played" ),
    new Card( "22", "Chaos", "Ditto",                    4, "Copy another card already played" ),
    new Card( "23", "Chaos", "Ditto",                    4, "Copy another card already played" ),
    new Card( "24", "Chaos", "Ditto",                    4, "Copy another card already played" ),
    new Card( "25", "Chaos", "Diversify Your Crop",      4, "Exchange 1 of each resource for 15WB" ),
    new Card( "26", "Chaos", "Double Cross",             4, "Before a battle, all Reapers in the enemy tile join your forces" ),
    new Card( "27", "Chaos", "Double Down",              4, "During a Harvest Phase, receive twice as many War-Bucks" ),
    new Card( "28", "Chaos", "Dualism",                  4, "Immediately, replace this card with 2 new Chaos Cards" ),
    new Card( "29", "Chaos", "Epiphany",                 4, "Receive 1 Technology or Doctrine" ),
    new Card( "30", "Chaos", "Espionage",                4, "Take a random Chaos Card from another player" ),
    new Card( "31", "Chaos", "Espionage",                4, "Take a random Chaos Card from another player" ),
    new Card( "32", "Chaos", "Espionage",                4, "Take a random Chaos Card from another player" ),
    new Card( "33", "Chaos", "Exclusive Card Club",      4, "No other player may purchase a Chaos Card this round" ),
    new Card( "34", "Chaos", "Exhaust",                  4, "Choose a district and for 1 round, its owner may not use the units in that district" ),
    new Card( "35", "Chaos", "Famine",                   4, "All other players must discard all resources" ),
    new Card( "36", "Chaos", "Fortitude",                4, "Ignore the effects of the Global Disaster" ),
    new Card( "37", "Chaos", "Friendly Fire",            4, "During a battle, for each of your enemy’s hits, they must remove 1 Reaper" ),
    new Card( "38", "Chaos", "Friendly Terms",           4, "At the end of a round, anyone you did not battle must pay you 3WB" ),
    new Card( "39", "Chaos", "Front Lines",              4, "Before a battle, remove all of your enemy’s Reapers and Boomers in the tile you are attacking" ),
    new Card( "40", "Chaos", "Gamebreaker",              4, "Move the Doomsday Clock to any round" ),
    new Card( "41", "Chaos", "Get Outta Dodge",          4, "If invaded, before your enemy can take your district, move all their attacking units to another tile" ),
    new Card( "42", "Chaos", "Gideon’s Ruse",            4, "Choose a tile and its units to battle another without the option of retreat" ),
    new Card( "43", "Chaos", "Give Me Your Tired…",      4, "Steal 5 Initiative Tokens from another player" ),
    new Card( "44", "Chaos", "Go to Jail",               4, "Choose a player to skip the Expansion Phase" ),
    new Card( "45", "Chaos", "Great Awakening",          4, "Spread an active religion to 3 districts" ),
    new Card( "46", "Chaos", "Hand of God",              4, "Receive 1 Godhand" ),
    new Card( "47", "Chaos", "Hands of Fate",            4, "During a battle, re-roll up to 7 misses" ),
    new Card( "48", "Chaos", "Heaven’s Gates",           4, "Receive 1 VP" ),
    new Card( "49", "Chaos", "Heaven’s Gates",           4, "Receive 1 VP" ),
    new Card( "50", "Chaos", "Heaven’s Gates",           4, "Receive 1 VP" ),
    new Card( "51", "Chaos", "Heaven’s Gates",           4, "Receive 1 VP" ),
    new Card( "52", "Chaos", "Heaven’s Gates",           4, "Receive 1 VP" ),
    new Card( "53", "Chaos", "Heaven’s Gates",           4, "Receive 1 VP" ),
    new Card( "54", "Chaos", "Heaven’s Gates",           4, "Receive 1 VP" ),
    new Card( "55", "Chaos", "Identity Crisis",          4, "For 1 round, choose 1 player to lose their Faction-specific ability" ),
    new Card( "56", "Chaos", "Inspired Leadership",      4, "Receive 2 Initiative Tokens" ),
    new Card( "57", "Chaos", "Laissez-faire",            4, "For 1 round, all trades must be agreed on by you" ),
    new Card( "58", "Chaos", "Manifest Destiny",         4, "All units can found districts" ),
    new Card( "59", "Chaos", "March through the Night",  4, "For 1 round, all units have a move range of 4" ),
    new Card( "60", "Chaos", "Master of the Domain",     4, "Receive 1 Reaper on every district" ),
    new Card( "61", "Chaos", "Men of Steel",             4, "For 1 round, all units receive +1 hit deflection" ),
    new Card( "62", "Chaos", "Micronization",            4, "Receive +2 tile unit capacity" ),
    new Card( "63", "Chaos", "Monopoly",                 4, "Claim a resource and each player must give you all of that resource that they own" ),
    new Card( "64", "Chaos", "Muscle Out",               4, "During the Continental Elections, choose 1 player that cannot be elected" ),
    new Card( "65", "Chaos", "Nepotism",                 4, "Pay the minimum bid price for an Auction lot" ),
    new Card( "66", "Chaos", "Parks Project",            4, "Exchange 1 Cultural Initiative Token for 1 Garden" ),
    new Card( "67", "Chaos", "Penny Stocks",             4, "For 1 round, invest for the Gambler's Gambit regardless of what round it is" ),
    new Card( "68", "Chaos", "Persecution",              4, "Choose a religion and purge all disciple tokens of that religion" ),
    new Card( "69", "Chaos", "Pioneers",                 4, "Receive 1 district" ),
    new Card( "70", "Chaos", "Power Struggle",           4, "During the Council Phase, no player may claim victory" ),
    new Card( "71", "Chaos", "Prophetic Vision",         4, "Skip the necessary prerequisites for an advancement" ),
    new Card( "72", "Chaos", "Public Arts",              4, "Exchange 1 Political Initiative Token for 2 Doctrines" ),
    new Card( "73", "Chaos", "Puppeteer",                4, "During the Continental Elections, choose the elected office to be voted on (trumps Minister of Foreign Affairs)" ),
    new Card( "74", "Chaos", "Reign of Terror",          4, "Perform an Inquisition" ),
    new Card( "75", "Chaos", "Return on Investment",     4, "For 1 round, you may sell Initiative Tokens for War-Bucks equal to your Victory Points total" ),
    new Card( "76", "Chaos", "Sacred Shrine",            4, "Build a Wonder in a non-Capital district with a religion for free" ),
    new Card( "77", "Chaos", "Scorched Earth",           4, "Upon being invaded, raze and loot your own district for 10WB" ),
    new Card( "78", "Chaos", "Scourge",                  4, "For 1 round, ignore Gardens when invading districts" ),
    new Card( "79", "Chaos", "Seductress",               4, "Take the Office Card from a player previously elected" ),
    new Card( "80", "Chaos", "Setting the Agenda",       4, "Look at and rearrange the top five Chaos Cards" ),
    new Card( "81", "Chaos", "Shifting Culture",         4, "Exchange types of Initiative Tokens" ),
    new Card( "82", "Chaos", "Shut Up",                  4, "When a card is played, cancel its effects" ),
    new Card( "83", "Chaos", "Shut Up",                  4, "When a card is played, cancel its effects" ),
    new Card( "84", "Chaos", "Shut Up",                  4, "When a card is played, cancel its effects" ),
    new Card( "85", "Chaos", "Shut Up",                  4, "When a card is played, cancel its effects" ),
    new Card( "86", "Chaos", "Shut Up",                  4, "When a card is played, cancel its effects" ),
    new Card( "87", "Chaos", "Silent Auction",           4, "Choose a player to not participate in an Auction" ),
    new Card( "88", "Chaos", "Sneak Attack",             4, "At the end of the Expansion Phase, take a second turn" ),
    new Card( "89", "Chaos", "Space Race",               4, "Exchange 1 Political Initiative Token for 2 Technologies" ),
    new Card( "90", "Chaos", "Spiritual Warfare",        4, "All units can spread religion; can spread religion to adjacent tiles if The Holy Empire" ),
    new Card( "91", "Chaos", "Squelch the Rebellion",    4, "When enacting an Annexation, Cultural Initiative Tokens cannot be used to defend" ),
    new Card( "92", "Chaos", "Strategic Maneuvers",      4, "Transport all units in 1 tile to any non-enemy tiles" ),
    new Card( "93", "Chaos", "Strongholds",              4, "If invading a district with a population of 5, all units receive +1 on combat rolls" ),
    new Card( "94", "Chaos", "Tax Refund",               4, "Receive 10WB" ),
    new Card( "95", "Chaos", "The Claw",                 4, "Remove 1 unit on the map that is not a Godhand or Hero" ),
    new Card( "96", "Chaos", "The Great Train Robbery",  4, "Take half of another player’s War-Bucks" ),
    new Card( "97", "Chaos", "The Swap",                 4, "Switch control of 1 of your districts with another player’s district (not the Capital); units in the districts switch locations" ),
    new Card( "98", "Chaos", "Tithing",                  4, "Receive 1WB for each district with a religion you founded" ),
    new Card( "99", "Chaos", "Way of the Samurai",       4, "For 1 round, receive 1WB for each of your units killed" )
];